import CustomSelect from './CustomSelect.js';
import * as Tools from '../tools.js';

/**
 * Filter.
 */
class Filter {
    /**
     * Construct the filter form.
     *
     * @param {Element} el Form element
     */
    constructor(el) {
        this._form = el;

        /**
         * Currently set filters. Values will be dynamically generated by the value of the `data-filter-type` attribute
         * value. Inputs without this attribute will be collected in the property filter.
         *
         * @type {Object}
         # @property {Object} filters.filter Will be collected in this property if no attribute value is set
         */
        this.filters = {};

        this._form.addEventListener('submit', this._formSubmitListener.bind(this));
        this._form.addEventListener('change', this._formChangeListener.bind(this));

        let selectFields = this._form.querySelectorAll('select');

        this.customSelects = new Set();

        selectFields.forEach(el => this.customSelects.add(new CustomSelect(el)));
    }

    /**
     * Update select options of specified id/name. This will overwrite the available options.
     *
     * @param {String} key id or name of the select field
     * @param {Array} options {@link CustomSelect#selectOptions}
     */
    updateSelectOptions(key, options) {
        let customSelect = this._getCustomSelectByKey(key);

        customSelect.setOptions(options);
    }

    /**
     * Get filter values of current filter form.
     *
     * @returns {Object} {@link Filter#filters}
     */
    getFilter() {
        let formData = new FormData(this._form);

        for (let entry of formData.entries()) {
            let filterType = this._getInputFilterType(entry[0]);

            if (filterType && !this.filters[filterType]) {
                this.filters[filterType] = {};
            }

            this.filters[filterType][entry[0]] = entry[1];
        }

        return Tools.cleanEmptyStringsFromObject(this.filters);
    }

    /**
     * Get custom select object by specified id/name.
     *
     * @param {String} key id/name of input
     * @private
     */
    _getCustomSelectByKey(key) {
        let customSelect;

        for (let entry of this.customSelects.values()) {
            if (entry.getName() === key) {
                customSelect = entry;

                break;
            }
        }

        return customSelect;
    }

    /**
     * Handle form submissions.
     *
     * @param {Event} e Submit event
     * @private
     */
    _formSubmitListener(e) {
        e.preventDefault();

        this.filters = this.getFilter();

        this._form.dispatchEvent(new CustomEvent('filter', {
            detail: {
                Filter: this,
                currentFilter: this.filters,
            },
        }));
    }

    /**
     * Handle form changes.
     *
     * @param {Event} e Changehange event
     * @private
     */
    _formChangeListener() {
        this.filters = this.getFilter();

        this._form.dispatchEvent(new CustomEvent('filterChange', {
            detail: {
                Filter: this,
                currentFilter: this.filters,
            },
        }));
    }

    /**
     * Get input type of filter element based on the node element.
     *
     * @param {string} key id/name of given element
     * @returns {string|string} filter type of the element
     * @private
     */
    _getInputFilterType(key) {
        let el = this._form.querySelector(`[name="${key}"]`);

        return el.dataset.filterType ? el.dataset.filterType : 'filter';
    }
}

export default Filter;
